Add looping option for player [EDI-905]
editframe/embed pull request #14
Opened 2023-02-24 03:52 UTC by IliasHad

2023-02-24 17:45 UTC, brycedev requested changes
this should be an option at instantiation vs. a method call 

Embed({loop: true})

2023-02-27 05:59 UTC, IliasHad commented
@brycedev Can you check it now ?

2023-02-27 15:33 UTC, brycedev requested changes

2023-02-27 15:33 UTC, brycedev commented on src/Embed.ts
> +    this.handlePlayerLoop()
we don't want to call this during handleEditorReady

looping should just work at instantiation by passing it into preview, not triggering it from a method

2023-02-27 15:33 UTC, brycedev commented on src/Embed.ts
> +      console.log(await this.sendCallWithValue("setPlayerLoop", {
remove this console.log

2023-02-27 15:35 UTC, IliasHad commented on src/Embed.ts
> +      console.log(await this.sendCallWithValue("setPlayerLoop", {
Okey

2023-02-27 15:36 UTC, IliasHad commented on src/Embed.ts
> +    this.handlePlayerLoop()
I tried to have it as config but it doesn't seem to work on my end, maybe the iframe wasn´t ready to send the event to it

2023-03-22 04:20 UTC, closed without merging