Add player and pause controls methods [EDI-893]
editframe/embed pull request #5
Opened 2023-02-18 17:46 UTC by IliasHad

2023-02-19 02:02 UTC, brycedev requested changes
i'm not seeing ```public play = ``` and ```public pause = ```

these should be calling updatePlayerState(false) or updatePlayerState(true) right?

2023-02-20 14:16 UTC, brycedev commented
i know. i'm saying we need play and pause. these are end user methods. i want them to be able to call .play() and .pause() . they shouldn't need to know about .updatePlayerState()

2023-02-20 20:18 UTC, IliasHad reviewed
Done :)

2023-02-20 20:19 UTC, brycedev approved these changes

2023-02-20 20:21 UTC, merged